### ISSUE TITLE
Tweaks to mobile site

### ISSUE THREAD

**Issue by bmorcos** [abr/abr.github.io#37]
I was checking out the website on my phone and noticed a couple things. Viewed with Android 9 (pie) and chrome browser.

When you click the hamburger menu icon, the options are super hard to read. I imagine we want a background here for the menu or something. Note, the `products` sub-menu _does_ come up with a white background.
![Screenshot_menu](https://user-images.githubusercontent.com/18405463/56964415-26c84100-6b29-11e9-8586-36080ca0baab.jpg)

The news section is not super readable, maybe for mobile we don't have all the Nengo versions floating on the right?
![Screenshot_news](https://user-images.githubusercontent.com/18405463/56964416-26c84100-6b29-11e9-9357-4dd95cf42c9b.jpg)

On the `Adaptive Control` page the `contact us` button is off center.
![Screenshot_adaptive](https://user-images.githubusercontent.com/18405463/56964417-26c84100-6b29-11e9-9c3d-6eadeb7d02ef.jpg)

**Comment by krisfrenette** [comment]
This is a good call out. I noticed this stuff as well

**Comment by tbekolay** [comment]
These issues were fixed in #46.
