### ISSUE TITLE
Review the Brain Board page

### ISSUE THREAD

**Issue by bmorcos** [abr/abr.github.io#39]
Now that NengoFPGA is starting to become more stable and commercial we should make sure the Brain Board page is accurate and up to date.

- I believe we are moving to selling _only_ software, so we should remove the "hardware package" from the purchase options.
- The last paragraph of the blurb alludes to out-of-the-box examples which aren't necessarily impemented (eg. voice recognition). Review this once we finish all the examples for NengoFPGA

**Comment by krisfrenette** [comment]
Closing this out so team FPGA can add it to their back log.
