### ISSUE TITLE
Add What we Offer to the front page scoller bar

### ISSUE THREAD

**Issue by PeterSuma** [abr/abr.github.io#6]
Add the bullets from the company presentation what we offer page to the scroller bar (the messages that pop up in front on the home page..currently open culture, inspired by the brain, etc...). 

Add a new one:

                                                                  What We Offer
New algorithms for dynamic neural processing. A uniquely powerful development platform. Low power, advanced neural networks.

This leads to a new page which is a summary of slides 2,3,4 and 5 from the deck. It positions us as extension to deep learning and articulates very clearly what we offer. Could also consider putting that on the Nengo product page but a direct what we offer page is compelling.

**Comment by krisfrenette** [comment]
With the new site up, this has been fixed.
